# Generated by Django 5.0.3 on 2024-04-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('auth_role', models.IntegerField(default=0)),
                ('auth_code', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, default='')),
                ('status', models.CharField(max_length=20)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('img_url', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='xPloreBlog.author')),
                ('tag', models.ManyToManyField(to='xPloreBlog.tag')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cauthors', to='xPloreBlog.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cposts', to='xPloreBlog.post')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
