# Generated by Django 5.0.3 on 2024-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0002_author_tag_post_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='auth_avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
