# Generated by Django 5.0.3 on 2024-04-15 14:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0003_author_auth_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
