# Generated by Django 5.0.3 on 2024-04-18 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0006_alter_post_excerpt_alter_post_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
