# Generated by Django 5.0.3 on 2024-04-18 18:51

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0007_postcomment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_text', ckeditor.fields.RichTextField()),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_by', models.CharField(default='parmodchd', max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(default='parmodchd', max_length=100)),
                ('updated_on', models.DateField()),
                ('r_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='xPloreBlog.postcomment')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
