# Generated by Django 5.0.3 on 2024-04-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0008_remove_postcomment_author_postcomment_reader_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='rating',
        ),
    ]
