# Generated by Django 5.0.3 on 2024-04-24 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0014_alter_postcomment_reader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
