# Generated by Django 5.0.3 on 2024-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0027_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
