# Generated by Django 5.0.3 on 2024-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0028_alter_reply_created_by_alter_reply_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
