# Generated by Django 5.0.3 on 2024-05-15 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0030_alter_post_created_by_alter_post_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(default=1, max_length=50)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.CharField(default=1, max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(default=1, max_length=100)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(default=1, max_length=50)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.CharField(default=1, max_length=100)),
                ('created_on', models.DateField()),
                ('updated_by', models.CharField(default=1, max_length=100)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='entity_type',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='xPloreBlog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='xPloreBlog.status'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='xPloreBlog.tag'),
        ),
    ]
