# Generated by Django 5.0.3 on 2024-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0031_category_status_tag_entity_type_remove_post_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='entity_type',
            field=models.CharField(default='Project Management', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='entity_type',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='entity_type',
            field=models.CharField(default='How', max_length=50),
        ),
    ]
