# Generated by Django 5.0.3 on 2024-05-15 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0032_alter_category_entity_type_alter_status_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='posts', to='xPloreBlog.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='categories', to='xPloreBlog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default='Active', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='statuses', to='xPloreBlog.status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='xPloreBlog.tag'),
        ),
    ]
