# Generated by Django 5.0.3 on 2024-05-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0033_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='entity_type',
            field=models.CharField(default='Blog', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Project Planning', max_length=75),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='entity_type',
            field=models.CharField(default='Blog', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='Active', max_length=75),
        ),
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='entity_type',
            field=models.CharField(default='Blog', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(default='How', max_length=75),
        ),
    ]
