# Generated by Django 5.0.3 on 2024-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0039_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', 'Stakeholder Management'), ('3', 'Resource Optimization'), ('4', 'Continuous Improvement'), ('5', 'Agile Project Management'), ('6', 'Project Management Office')], default=1, max_length=50),
        ),
    ]
