# Generated by Django 5.0.3 on 2024-05-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0040_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
