# Generated by Django 5.0.3 on 2024-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPloreBlog', '0043_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Project Planning', 'Project Planning'), ('Stakeholder Management', 'Stakeholder Management'), ('Resource Optimization', 'Resource Optimization'), ('Continuous Improvement', 'Continuous Improvement'), ('Agile Project Management', 'Agile Project Management'), ('Project Management Office', 'Project Management Office')], max_length=50),
        ),
    ]
